---
apiVersion: v1
kind: PersistentVolume
metadata:
  name : test-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 200Gi
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    fsType: ext4
    pdName: test-disk
