apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-test
spec:
  accessModes:
     - ReadOnlyMany
     #- ReadWriteOnce
     #- ReadWriteMany
  resources:
    requests:
      storage: 2Gi
