apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-standard
spec:
  accessModes:
    #- ReadOnlyMany
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
