apiVersion: v1
kind: Pod
metadata:
  name: sleeper
spec:
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: test-pvc
  containers:
    - name: busybox
      image: gcr.io/google_containers/busybox
      command:
        - sleep
        - "6000"
      volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false